# Change the prefix key to C-j
unbind C-b
set -g prefix C-j

# Enable mouse operation
set-option -g mouse on

# Reload configuration
bind r source-file ~/.tmux.conf \; display "Reloaded!"

## --------------------Panes--------------------

# Move between panes using vim keybindings
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes using vim keybindings
bind -r H resize-pane -L 30
bind -r J resize-pane -D 30
bind -r K resize-pane -U 30
bind -r L resize-pane -R 30

# Split pane vertically
bind v split-window -h -c '#{pane_current_path}'
# Split pane horizontally
bind s split-window -v -c '#{pane_current_path}'

# Display pane numbers
bind i display-panes

# Close pane
bind q kill-pane
